#ifndef _KEYCONTEXT_H
#define _KEYCONTEXT_H

/* VOLUMNE BRIGHTNESS VALUES */
#define MIN_VOLUME 0
#define MAX_VOLUME 20
#define MIN_BRIGHTNESS 1
#define MAX_BRIGHTNESS 10

/* INPUT CODES */
#define CODE_NONE 0
#define CODE_UP SDLK_UP
#define CODE_DOWN SDLK_DOWN
#define CODE_LEFT SDLK_LEFT
#define CODE_RIGHT SDLK_RIGHT
#define CODE_A SDLK_SPACE
#define CODE_B SDLK_LCTRL
#define CODE_X SDLK_LSHIFT
#define CODE_Y SDLK_LALT
#define CODE_START SDLK_RETURN
#define CODE_SELECT SDLK_RCTRL
#define CODE_MENU SDLK_ESCAPE
#define CODE_POWER SDLK_POWER
#define CODE_L1 SDLK_e
#define CODE_L2 SDLK_TAB
#define CODE_R1 SDLK_t
#define CODE_R2 SDLK_BACKSPACE
#define CODE_PLUS SDLK_LSUPER
#define CODE_MINUS SDLK_RSUPER

/* KEYMON MAPS */
#define BUTTON_UP KEY_UP
#define BUTTON_DOWN KEY_DOWN
#define BUTTON_LEFT KEY_LEFT
#define BUTTON_RIGHT KEY_RIGHT
#define BUTTON_A KEY_SPACE
#define BUTTON_B KEY_LEFTCTRL
#define BUTTON_X KEY_LEFTSHIFT
#define BUTTON_Y KEY_LEFTALT
#define BUTTON_L1 KEY_E
#define BUTTON_R1 KEY_T
#define BUTTON_L2 KEY_TAB
#define BUTTON_R2 KEY_BACKSPACE
#define BUTTON_SELECT KEY_RIGHTCTRL
#define BUTTON_START KEY_ENTER
#define BUTTON_MENU KEY_ESC
#define BUTTON_POWER KEY_POWER
#define BUTTON_VOLUP KEY_VOLUMEUP
#define BUTTON_VOLDOWN KEY_VOLUMEDOWN


#endif